-- AquaScheme: complete database bootstrap.
-- GENERATED by scripts/build-bootstrap.mjs — do not edit by hand.
-- Run once in the Supabase SQL editor. Safe to re-run: every part is idempotent.
-- Sources, in order: 0000_full_schema.sql, 0003_update1.sql, 0004_existing_isolated.sql, 0005_norm_registry.sql, 0006_regions.sql, 0007_geology.sql, 0008_drainage.sql, 0009_norm_sources.sql, 0010_norm_clause_note.sql, 0011_basis.sql, 0012_engineering_route.sql, 0013_manhole_catalog.sql, 0014_dataset_uniqueness.sql, 0015_basis_file_atomic.sql, 0016_pump_catalog.sql, 0017_title_block.sql, 0018_master_plan.sql, 0019_vertical_plan.sql, 0020_gravity_basins.sql, 0021_technical_conditions.sql

-- ============================================================
-- BEGIN 0000_full_schema.sql
-- ============================================================
-- AquaScheme: full database schema (consolidated and idempotent).
-- Run this ONCE in Supabase SQL Editor. Safe to re-run if needed.
-- This replaces running 0001_init.sql and 0002_equipment.sql separately.

-- ============================================================
-- 1. PROFILES
-- ============================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 2. PROJECTS
-- ============================================================
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists projects_owner_id_idx on public.projects (owner_id);
alter table public.projects enable row level security;

drop policy if exists "projects_all_own" on public.projects;
create policy "projects_all_own" on public.projects
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

create or replace function public.is_project_owner(project uuid)
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1 from public.projects p
    where p.id = project and p.owner_id = (select auth.uid())
  );
$$;

-- ============================================================
-- 3. DATASETS
-- ============================================================
create table if not exists public.datasets (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  kind text not null,
  file_name text,
  storage_path text,
  content jsonb,
  meta jsonb,
  created_at timestamptz not null default now(),
  constraint datasets_project_kind_unique unique (project_id, kind)
);
create index if not exists datasets_project_id_idx on public.datasets (project_id);
alter table public.datasets enable row level security;

drop policy if exists "datasets_all_own" on public.datasets;
create policy "datasets_all_own" on public.datasets
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 4. BUILDINGS
-- ============================================================
create table if not exists public.buildings (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  label text,
  x double precision not null,
  y double precision not null,
  ground_elevation double precision,
  floors integer not null default 1 check (floors >= 1),
  residents integer check (residents >= 0),
  specific_demand_lpd double precision,
  created_at timestamptz not null default now()
);
create index if not exists buildings_project_id_idx on public.buildings (project_id);
alter table public.buildings enable row level security;

drop policy if exists "buildings_all_own" on public.buildings;
create policy "buildings_all_own" on public.buildings
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 5. NODES
-- ============================================================
create table if not exists public.nodes (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  kind text not null,
  label text,
  x double precision not null,
  y double precision not null,
  ground_elevation double precision,
  demand_lps double precision,
  building_id uuid references public.buildings (id) on delete set null,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists nodes_project_id_idx on public.nodes (project_id);
alter table public.nodes enable row level security;

drop policy if exists "nodes_all_own" on public.nodes;
create policy "nodes_all_own" on public.nodes
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 6. PIPES
-- ============================================================
create table if not exists public.pipes (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  from_node uuid not null references public.nodes (id) on delete cascade,
  to_node uuid not null references public.nodes (id) on delete cascade,
  length_m double precision,
  diameter_mm double precision,
  material text,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists pipes_project_id_idx on public.pipes (project_id);
alter table public.pipes enable row level security;

drop policy if exists "pipes_all_own" on public.pipes;
create policy "pipes_all_own" on public.pipes
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 7. CALC_RUNS
-- ============================================================
create table if not exists public.calc_runs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  status text not null default 'pending',
  params jsonb,
  summary jsonb,
  error text,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists calc_runs_project_id_idx on public.calc_runs (project_id);
alter table public.calc_runs enable row level security;

drop policy if exists "calc_runs_all_own" on public.calc_runs;
create policy "calc_runs_all_own" on public.calc_runs
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 8. EXPORTS
-- ============================================================
create table if not exists public.exports (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  calc_run_id uuid references public.calc_runs (id) on delete set null,
  kind text not null,
  file_name text,
  storage_path text not null,
  created_at timestamptz not null default now()
);
create index if not exists exports_project_id_idx on public.exports (project_id);
alter table public.exports enable row level security;

drop policy if exists "exports_all_own" on public.exports;
create policy "exports_all_own" on public.exports
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 9. DATASETS kind constraint (includes equipment)
-- ============================================================
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit'
  ));

-- ============================================================
-- 10. STORAGE: private buckets and owner only access
-- ============================================================
insert into storage.buckets (id, name, public)
values ('source-files', 'source-files', false), ('exports', 'exports', false)
on conflict (id) do nothing;

drop policy if exists "storage_owner_all" on storage.objects;
create policy "storage_owner_all" on storage.objects
  for all
  using (
    bucket_id in ('source-files', 'exports')
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id in ('source-files', 'exports')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- ============================================================
-- 11. ENGINEERING ROUTE STATE (equivalent to migration 0012)
-- ============================================================
alter table public.projects add column if not exists route_status text not null default 'stale';
alter table public.projects drop constraint if exists projects_route_status_check;
alter table public.projects add constraint projects_route_status_check
  check (route_status in ('stale', 'blocked', 'preliminary', 'calculated'));
alter table public.projects add column if not exists route_algorithm_version text;
alter table public.projects add column if not exists route_input_hash text;
alter table public.projects add column if not exists input_data_hash text;
alter table public.projects add column if not exists route_quality jsonb not null default '{}'::jsonb;
alter table public.projects add column if not exists route_warnings jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists route_blockers jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists calculation_warnings jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists calculation_blockers jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists route_report jsonb not null default '{}'::jsonb;
alter table public.projects add column if not exists route_calculated_at timestamptz;
alter table public.projects add column if not exists network_revision bigint not null default 0;

alter table public.buildings add column if not exists design_flow_lps double precision;
update public.buildings
set design_flow_lps = specific_demand_lpd,
    specific_demand_lpd = null
where design_flow_lps is null
  and specific_demand_lpd is not null
  and (upper(coalesce(label, '')) like 'ОС %' or upper(coalesce(label, '')) like 'OC %' or upper(coalesce(label, '')) like 'OS %');
alter table public.nodes add column if not exists system_type text;
alter table public.nodes add column if not exists design_flow_lps double precision;
alter table public.nodes add column if not exists invert_elevation_m double precision;
alter table public.nodes add column if not exists source_entity text;
alter table public.nodes add column if not exists data_source text;
alter table public.nodes drop constraint if exists nodes_kind_check;
alter table public.nodes add constraint nodes_kind_check check (kind in (
  'source', 'junction', 'hydrant', 'valve', 'air_valve', 'drain', 'well',
  'ring', 'cross', 'building', 'facility_inflow', 'lns_inlet', 'lns_outlet',
  'outlet', 'manhole', 'terrain_break', 'treatment_facility',
  'pumping_station', 'gravity_inlet', 'pressure_outlet', 'chamber',
  'outfall', 'crossing', 'transition', 'inspection_node'
));
alter table public.pipes add column if not exists engineering_kind text;
alter table public.pipes add column if not exists system_type text;
alter table public.pipes add column if not exists parallel_count integer not null default 1;
alter table public.pipes add column if not exists alignment jsonb;
alter table public.pipes add column if not exists source_layer text;
alter table public.pipes add column if not exists source_entity text;
alter table public.pipes add column if not exists flow_direction text;
alter table public.pipes add column if not exists inner_diameter_mm double precision;
alter table public.pipes add column if not exists sdr double precision;
alter table public.pipes add column if not exists sn double precision;
alter table public.pipes add column if not exists pn double precision;
alter table public.pipes add column if not exists roughness_mm double precision;
alter table public.pipes add column if not exists slope double precision;
alter table public.pipes add column if not exists start_invert_m double precision;
alter table public.pipes add column if not exists end_invert_m double precision;
alter table public.pipes add column if not exists cover_m double precision;
alter table public.pipes add column if not exists design_flow_lps double precision;
alter table public.pipes add column if not exists velocity_mps double precision;
alter table public.pipes add column if not exists filling_ratio double precision;
alter table public.pipes add column if not exists pressure_m double precision;
alter table public.pipes add column if not exists calculation_status text not null default 'unverified';
alter table public.pipes add column if not exists data_source text;

drop function if exists public.replace_project_network(uuid, jsonb, jsonb, text, text, text, jsonb, jsonb);
create or replace function public.replace_project_network(
  p_project_id uuid,
  p_nodes jsonb,
  p_pipes jsonb,
  p_route_status text,
  p_algorithm_version text,
  p_input_hash text,
  p_warnings jsonb default '[]'::jsonb,
  p_blockers jsonb default '[]'::jsonb,
  p_report jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
set search_path = public, pg_temp
as $$
declare next_revision bigint;
begin
  if not public.is_project_owner(p_project_id) then raise exception 'project access denied'; end if;
  if p_route_status not in ('blocked', 'preliminary', 'calculated') then raise exception 'invalid route status'; end if;
  create temporary table route_node_map (engine_id text primary key, db_id uuid not null, payload jsonb not null) on commit drop;
  insert into route_node_map select item ->> 'id', gen_random_uuid(), item from jsonb_array_elements(coalesce(p_nodes, '[]'::jsonb)) item;
  delete from public.pipes where project_id = p_project_id;
  delete from public.nodes where project_id = p_project_id;
  insert into public.nodes (id, project_id, kind, label, x, y, ground_elevation, demand_lps, design_flow_lps, invert_elevation_m, system_type, building_id, source_entity, data_source, meta)
  select m.db_id, p_project_id, coalesce(m.payload ->> 'kind', 'junction'), coalesce(m.payload ->> 'label', m.engine_id),
    (m.payload ->> 'x')::double precision, (m.payload ->> 'y')::double precision,
    nullif(m.payload ->> 'groundElevation', '')::double precision, nullif(m.payload ->> 'designFlowLps', '')::double precision,
    nullif(m.payload ->> 'designFlowLps', '')::double precision, nullif(m.payload ->> 'invertElevationM', '')::double precision,
    m.payload ->> 'systemType', nullif(m.payload ->> 'buildingId', '')::uuid, m.payload ->> 'sourceEntity', m.payload ->> 'dataSource',
    jsonb_build_object('engineKind', m.payload ->> 'kind', 'engineId', m.engine_id)
  from route_node_map m;
  insert into public.pipes (
    project_id, from_node, to_node, length_m, diameter_mm, material,
    engineering_kind, system_type, parallel_count, alignment, source_layer,
    source_entity, flow_direction, inner_diameter_mm, sdr, sn, pn,
    roughness_mm, slope, start_invert_m, end_invert_m, cover_m,
    design_flow_lps, velocity_mps, filling_ratio, pressure_m,
    calculation_status, data_source, meta
  )
  select p_project_id, f.db_id, t.db_id, nullif(item ->> 'lengthM', '')::double precision,
    nullif(item ->> 'diameterMm', '')::double precision, item ->> 'material', item ->> 'kind', item ->> 'systemType',
    greatest(1, coalesce(nullif(item ->> 'parallelCount', '')::integer, 1)), item -> 'alignment', item ->> 'sourceLayer',
    item ->> 'sourceEntity', item ->> 'flowDirection',
    nullif(item ->> 'innerDiameterMm', '')::double precision,
    nullif(item ->> 'sdr', '')::double precision,
    nullif(item ->> 'sn', '')::double precision,
    nullif(item ->> 'pn', '')::double precision,
    nullif(item ->> 'roughnessMm', '')::double precision,
    nullif(item ->> 'slope', '')::double precision,
    nullif(item ->> 'startInvertM', '')::double precision,
    nullif(item ->> 'endInvertM', '')::double precision,
    nullif(item ->> 'coverM', '')::double precision,
    nullif(item ->> 'designFlowLps', '')::double precision,
    nullif(item ->> 'velocityMs', '')::double precision,
    nullif(item ->> 'fillingRatio', '')::double precision,
    nullif(item ->> 'pressureM', '')::double precision,
    coalesce(item ->> 'calculationStatus', 'unverified'), item ->> 'dataSource',
    jsonb_build_object('kind', item ->> 'kind', 'engineId', item ->> 'id')
  from jsonb_array_elements(coalesce(p_pipes, '[]'::jsonb)) item
  join route_node_map f on f.engine_id = item ->> 'fromNode'
  join route_node_map t on t.engine_id = item ->> 'toNode';
  update public.projects set route_status = p_route_status, route_algorithm_version = p_algorithm_version,
    route_input_hash = p_input_hash, input_data_hash = p_input_hash,
    route_warnings = coalesce(p_warnings, '[]'::jsonb), route_blockers = coalesce(p_blockers, '[]'::jsonb),
    calculation_warnings = coalesce(p_warnings, '[]'::jsonb), calculation_blockers = coalesce(p_blockers, '[]'::jsonb),
    route_report = coalesce(p_report, '{}'::jsonb), route_quality = coalesce(p_report, '{}'::jsonb),
    route_calculated_at = now(), network_revision = network_revision + 1
  where id = p_project_id returning network_revision into next_revision;
  return next_revision;
end;
$$;

create or replace function public.save_gravity_design(p_project_id uuid, p_result jsonb)
returns uuid language plpgsql set search_path = public, pg_temp as $$
declare item jsonb; run_id uuid;
begin
  if not public.is_project_owner(p_project_id) then raise exception 'project access denied'; end if;
  for item in select value from jsonb_array_elements(coalesce(p_result -> 'pipes', '[]'::jsonb)) loop
    update public.pipes set diameter_mm = nullif(item ->> 'diameterMm', '')::double precision,
      slope = nullif(item ->> 'slope', '')::double precision,
      design_flow_lps = nullif(item ->> 'flowLps', '')::double precision,
      velocity_mps = nullif(item ->> 'velocityMs', '')::double precision,
      filling_ratio = nullif(item ->> 'fillRatio', '')::double precision,
      calculation_status = case when jsonb_array_length(coalesce(item -> 'issues', '[]'::jsonb)) = 0 then 'calculated' else 'preliminary' end,
      meta = coalesce(meta, '{}'::jsonb) || jsonb_build_object(
        'flowLps', nullif(item ->> 'flowLps', '')::double precision,
        'velocityMs', nullif(item ->> 'velocityMs', '')::double precision,
        'slope', nullif(item ->> 'slope', '')::double precision,
        'fillRatio', nullif(item ->> 'fillRatio', '')::double precision)
    where project_id = p_project_id and meta ->> 'engineId' = item ->> 'id';
  end loop;
  insert into public.calc_runs (project_id, status, params, summary, finished_at)
  values (p_project_id, 'done', jsonb_build_object('system', p_result ->> 'systemType', 'outletFlowLps', p_result -> 'outletFlowLps'), p_result, now())
  returning id into run_id;
  return run_id;
end;
$$;
-- END 0000_full_schema.sql

-- ============================================================
-- BEGIN 0003_update1.sql
-- ============================================================
-- AquaScheme: requirements update 1 (M1).
-- Apply AFTER 0000_full_schema.sql. Idempotent: safe to re-run.
-- Adds: work type and system type on projects, user material catalogs,
-- land parcels, existing networks and survey acts for reconstruction.

-- ============================================================
-- 1. PROJECTS: work type and system type (wizard steps 1 and 2)
-- ============================================================
alter table public.projects
  add column if not exists work_type text not null default 'new'
    check (work_type in ('new', 'reconstruction'));

alter table public.projects
  add column if not exists system_type text not null default 'water'
    check (system_type in ('water', 'sewer', 'storm'));

-- ============================================================
-- 2. CATALOGS: user uploaded material and fittings catalogs.
--    The built in catalog lives in the engine code and is NOT stored
--    here; projects.active_catalog_id NULL means "built in".
-- ============================================================
create table if not exists public.catalogs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  name text not null,
  source_file text,
  created_at timestamptz not null default now()
);
create index if not exists catalogs_project_id_idx on public.catalogs (project_id);
alter table public.catalogs enable row level security;

drop policy if exists "catalogs_all_own" on public.catalogs;
create policy "catalogs_all_own" on public.catalogs
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

create table if not exists public.catalog_items (
  id uuid primary key default gen_random_uuid(),
  catalog_id uuid not null references public.catalogs (id) on delete cascade,
  item_type text not null check (item_type in ('pipe', 'valve', 'hydrant', 'air_valve', 'check_valve', 'fitting')),
  material text,
  standard text,
  dn integer,
  outer_mm double precision,
  wall_mm double precision,
  sdr double precision,
  pn double precision,
  roughness_mm double precision,
  price numeric,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists catalog_items_catalog_id_idx on public.catalog_items (catalog_id);
alter table public.catalog_items enable row level security;

drop policy if exists "catalog_items_all_own" on public.catalog_items;
create policy "catalog_items_all_own" on public.catalog_items
  for all using (
    exists (
      select 1 from public.catalogs c
      where c.id = catalog_id and public.is_project_owner(c.project_id)
    )
  )
  with check (
    exists (
      select 1 from public.catalogs c
      where c.id = catalog_id and public.is_project_owner(c.project_id)
    )
  );

alter table public.projects
  add column if not exists active_catalog_id uuid references public.catalogs (id) on delete set null;

-- ============================================================
-- 3. PARCELS: land plots of buildings and the route right of way.
--    geometry: GeoJSON Polygon in local project coordinates (meters).
-- ============================================================
create table if not exists public.parcels (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  building_id uuid references public.buildings (id) on delete set null,
  label text,
  kind text not null default 'parcel' check (kind in ('parcel', 'right_of_way')),
  geometry jsonb not null,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists parcels_project_id_idx on public.parcels (project_id);
alter table public.parcels enable row level security;

drop policy if exists "parcels_all_own" on public.parcels;
create policy "parcels_all_own" on public.parcels
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 4. EXISTING NETWORKS (reconstruction): imported segments.
--    Existing manholes are stored as rows in nodes
--    (meta.origin = 'existing'); segments reference them.
-- ============================================================
create table if not exists public.existing_pipes (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  from_node uuid not null references public.nodes (id) on delete cascade,
  to_node uuid not null references public.nodes (id) on delete cascade,
  length_m double precision,
  diameter_mm double precision,
  material text,
  laid_year integer,
  wear_percent double precision check (wear_percent >= 0 and wear_percent <= 100),
  roughness_mm double precision,
  decision text not null default 'keep' check (decision in ('keep', 'rehabilitate', 'replace')),
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists existing_pipes_project_id_idx on public.existing_pipes (project_id);
alter table public.existing_pipes enable row level security;

drop policy if exists "existing_pipes_all_own" on public.existing_pipes;
create policy "existing_pipes_all_own" on public.existing_pipes
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 5. SURVEY ACTS: structured technical survey data per segment,
--    plus the scanned PDF stored in the source-files bucket.
-- ============================================================
create table if not exists public.survey_acts (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  existing_pipe_id uuid references public.existing_pipes (id) on delete cascade,
  laid_year integer,
  material text,
  diameter_mm double precision,
  wear_percent double precision check (wear_percent >= 0 and wear_percent <= 100),
  defects text,
  overgrowth_percent double precision check (overgrowth_percent >= 0 and overgrowth_percent <= 100),
  scan_path text,
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists survey_acts_project_id_idx on public.survey_acts (project_id);
alter table public.survey_acts enable row level security;

drop policy if exists "survey_acts_all_own" on public.survey_acts;
create policy "survey_acts_all_own" on public.survey_acts
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));
-- END 0003_update1.sql

-- ============================================================
-- BEGIN 0004_existing_isolated.sql
-- ============================================================
-- AquaScheme: isolate the existing network (phase 17).
-- Apply AFTER 0003_update1.sql. Idempotent: safe to re-run.
-- Existing pipes store their endpoint coordinates in meta and no longer
-- require node rows, so the existing network stays fully separate from the
-- designed network in nodes/pipes (which is rebuilt on every trace/import).

alter table public.existing_pipes alter column from_node drop not null;
alter table public.existing_pipes alter column to_node drop not null;
-- END 0004_existing_isolated.sql

-- ============================================================
-- BEGIN 0005_norm_registry.sql
-- ============================================================
-- AquaScheme: norm registry and decision log (requirements update 2).
-- Apply AFTER 0004. Idempotent: safe to re-run.
-- Every decision the system makes must cite a normative clause. The engine
-- code is the source of truth for norm_documents/norm_clauses; the app mirrors
-- it here (upsert) so nothing drifts. decision_log stores per calc decisions.

-- ============================================================
-- 1. NORM DOCUMENTS and CLAUSES (shared reference data)
-- ============================================================
create table if not exists public.norm_documents (
  code text primary key,
  title text not null,
  edition text,
  status text not null default 'unverified' check (status in ('verified', 'unverified'))
);
alter table public.norm_documents enable row level security;

drop policy if exists "norm_documents_read" on public.norm_documents;
create policy "norm_documents_read" on public.norm_documents
  for select using (auth.uid() is not null);

drop policy if exists "norm_documents_write" on public.norm_documents;
create policy "norm_documents_write" on public.norm_documents
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

create table if not exists public.norm_clauses (
  id text primary key,
  document_code text not null references public.norm_documents (code) on delete cascade,
  clause text,
  requirement text not null,
  value_text text,
  units text,
  applies_system text[],
  applies_work text[],
  status text not null default 'unverified' check (status in ('verified', 'unverified'))
);
alter table public.norm_clauses enable row level security;

drop policy if exists "norm_clauses_read" on public.norm_clauses;
create policy "norm_clauses_read" on public.norm_clauses
  for select using (auth.uid() is not null);

drop policy if exists "norm_clauses_write" on public.norm_clauses;
create policy "norm_clauses_write" on public.norm_clauses
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

-- ============================================================
-- 2. DECISION LOG (per project / calc run)
-- ============================================================
create table if not exists public.decision_log (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  calc_run_id uuid references public.calc_runs (id) on delete cascade,
  key text not null,
  value_text text,
  norm_refs text[],
  inputs jsonb,
  basis text not null default 'normative' check (basis in ('normative', 'engineering', 'economic')),
  created_at timestamptz not null default now()
);
create index if not exists decision_log_project_id_idx on public.decision_log (project_id);
alter table public.decision_log enable row level security;

drop policy if exists "decision_log_all_own" on public.decision_log;
create policy "decision_log_all_own" on public.decision_log
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));
-- END 0005_norm_registry.sql

-- ============================================================
-- BEGIN 0006_regions.sql
-- ============================================================
-- AquaScheme: regions of Kazakhstan with regional design parameters
-- (requirements update 3, change 3). Apply AFTER 0005. Idempotent.
-- The engine code (engine/src/regions.ts) is the source of truth: the app
-- mirrors the list here on project open (upsert), the same convention as the
-- norm registry. Official seismic/freezing/rain values are pending from the
-- user, so every row starts unverified with null values.

-- ============================================================
-- 1. REGIONS (shared reference data)
-- ============================================================
create table if not exists public.regions (
  id text primary key,
  name text not null,
  kind text not null check (kind in ('oblast', 'city')),
  center_lon double precision not null,
  center_lat double precision not null,
  seismic_points numeric,
  freezing_depth_m numeric,
  rain_params jsonb,
  hazards text[] not null default '{}',
  status text not null default 'unverified' check (status in ('verified', 'unverified'))
);
alter table public.regions enable row level security;

drop policy if exists "regions_read" on public.regions;
create policy "regions_read" on public.regions
  for select using (auth.uid() is not null);

drop policy if exists "regions_write" on public.regions;
create policy "regions_write" on public.regions
  for all using (auth.uid() is not null) with check (auth.uid() is not null);

-- ============================================================
-- 2. Allow the region dataset kind (per project region selection)
-- ============================================================
alter table public.datasets drop constraint datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in ('topography', 'buildings', 'source', 'geology', 'seismic', 'normative', 'equipment', 'region'));
-- END 0006_regions.sql

-- ============================================================
-- BEGIN 0007_geology.sql
-- ============================================================
-- AquaScheme: geology module (requirements update 3, change 1).
-- Apply AFTER 0006. Idempotent: safe to re-run.
-- Geology becomes a full module: boreholes with coordinates and mouth
-- elevations, layers tied to engineering geological elements (ИГЭ), and the
-- groundwater table with aggressiveness per material. Project level
-- collapsibility, heaving, swelling and freezing depth live on the geology
-- dataset content; these tables hold the borehole data.

-- ============================================================
-- 1. BOREHOLES
-- ============================================================
create table if not exists public.geo_boreholes (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  label text not null,
  x double precision,
  y double precision,
  mouth_elevation_m double precision,
  created_at timestamptz not null default now()
);
create index if not exists geo_boreholes_project_id_idx on public.geo_boreholes (project_id);
alter table public.geo_boreholes enable row level security;

drop policy if exists "geo_boreholes_all_own" on public.geo_boreholes;
create policy "geo_boreholes_all_own" on public.geo_boreholes
  for all using (public.is_project_owner(project_id))
  with check (public.is_project_owner(project_id));

-- ============================================================
-- 2. LAYERS (per borehole, tied to an ИГЭ)
-- ============================================================
create table if not exists public.geo_layers (
  id uuid primary key default gen_random_uuid(),
  borehole_id uuid not null references public.geo_boreholes (id) on delete cascade,
  top_depth_m double precision not null,
  bottom_depth_m double precision not null,
  ige_code text,
  soil_name text,
  density_g_cm3 double precision,
  moisture_percent double precision,
  friction_angle_deg double precision,
  cohesion_kpa double precision,
  deformation_modulus_mpa double precision,
  filtration_m_day double precision,
  created_at timestamptz not null default now()
);
create index if not exists geo_layers_borehole_id_idx on public.geo_layers (borehole_id);
alter table public.geo_layers enable row level security;

drop policy if exists "geo_layers_all_own" on public.geo_layers;
create policy "geo_layers_all_own" on public.geo_layers
  for all using (
    exists (
      select 1 from public.geo_boreholes b
      where b.id = borehole_id and public.is_project_owner(b.project_id)
    )
  )
  with check (
    exists (
      select 1 from public.geo_boreholes b
      where b.id = borehole_id and public.is_project_owner(b.project_id)
    )
  );

-- ============================================================
-- 3. GROUNDWATER (one record per borehole)
-- ============================================================
create table if not exists public.geo_water (
  id uuid primary key default gen_random_uuid(),
  borehole_id uuid not null references public.geo_boreholes (id) on delete cascade,
  depth_m double precision,
  aggressiveness_steel text check (aggressiveness_steel in ('low', 'medium', 'high')),
  aggressiveness_concrete text check (aggressiveness_concrete in ('low', 'medium', 'high')),
  aggressiveness_pe text check (aggressiveness_pe in ('low', 'medium', 'high')),
  created_at timestamptz not null default now()
);
create index if not exists geo_water_borehole_id_idx on public.geo_water (borehole_id);
alter table public.geo_water enable row level security;

drop policy if exists "geo_water_all_own" on public.geo_water;
create policy "geo_water_all_own" on public.geo_water
  for all using (
    exists (
      select 1 from public.geo_boreholes b
      where b.id = borehole_id and public.is_project_owner(b.project_id)
    )
  )
  with check (
    exists (
      select 1 from public.geo_boreholes b
      where b.id = borehole_id and public.is_project_owner(b.project_id)
    )
  );
-- END 0007_geology.sql

-- ============================================================
-- BEGIN 0008_drainage.sql
-- ============================================================
-- AquaScheme: unified consumption, water → drainage link (requirements
-- update 3, change 4). Apply AFTER 0007. Idempotent: safe to re-run.
-- Specific wastewater discharge equals specific water demand without
-- irrigation (engine consumption.ts, norm drainage.equalsWater). A sewer
-- project may pull its flows from an existing water project — the single
-- source of truth — via water_source_project_id. When the water calc changes,
-- the sewer side is marked "требует пересчёта" (tracked in the drainage
-- dataset snapshot).

-- ============================================================
-- 1. Link a sewer project to its water supply project
-- ============================================================
alter table public.projects
  add column if not exists water_source_project_id uuid
    references public.projects (id) on delete set null;

-- ============================================================
-- 2. Allow the drainage dataset kind (per project drainage settings)
-- ============================================================
alter table public.datasets drop constraint datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in ('topography', 'buildings', 'source', 'geology', 'seismic', 'normative', 'equipment', 'region', 'drainage'));
-- END 0008_drainage.sql

-- ============================================================
-- BEGIN 0009_norm_sources.sql
-- ============================================================
-- AquaScheme: norm registry source tracking (norms base, PDFs in docs/norms).
-- Apply AFTER 0008. Idempotent: safe to re-run.
-- A clause may now record which official PDF and which PDF page its wording
-- was transcribed from. verify_page marks OCR doubt: digits must be re-checked
-- against the PDF by eye before the value is trusted.

alter table public.norm_documents add column if not exists source_file text;
alter table public.norm_documents add column if not exists note text;

alter table public.norm_clauses add column if not exists source_file text;
alter table public.norm_clauses add column if not exists source_page integer;
alter table public.norm_clauses add column if not exists verify_page boolean not null default false;
-- END 0009_norm_sources.sql

-- ============================================================
-- BEGIN 0010_norm_clause_note.sql
-- ============================================================
-- AquaScheme: free-form note on norm clauses (norms base НБ3).
-- Apply AFTER 0009. Idempotent: safe to re-run.
-- A clause may carry a note, e.g. why a foreign standard (ГОСТ Р) is used as a
-- methodological template while RK norms keep priority.

alter table public.norm_clauses add column if not exists note text;
-- END 0010_norm_clause_note.sql

-- ============================================================
-- BEGIN 0011_basis.sql
-- ============================================================
-- AquaScheme: initial permitting documents checklist (исходно-разрешительная
-- документация: ТЗ, АПЗ, ПДП, акт выбора трассы, схема генплана, топосъёмка,
-- отчёт ИГИ, вертикальная планировка, ТУ). Apply AFTER 0010. Idempotent.

alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis'
  ));
-- END 0011_basis.sql

-- ============================================================
-- BEGIN 0012_engineering_route.sql
-- ============================================================
-- AquaScheme: explicit engineering topology and atomic route replacement.
-- Apply AFTER 0011. Idempotent.

alter table public.projects add column if not exists route_status text not null default 'stale';
alter table public.projects drop constraint if exists projects_route_status_check;
alter table public.projects add constraint projects_route_status_check
  check (route_status in ('stale', 'blocked', 'preliminary', 'calculated'));
alter table public.projects add column if not exists route_algorithm_version text;
alter table public.projects add column if not exists route_input_hash text;
alter table public.projects add column if not exists input_data_hash text;
alter table public.projects add column if not exists route_quality jsonb not null default '{}'::jsonb;
alter table public.projects add column if not exists route_warnings jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists route_blockers jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists calculation_warnings jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists calculation_blockers jsonb not null default '[]'::jsonb;
alter table public.projects add column if not exists route_report jsonb not null default '{}'::jsonb;
alter table public.projects add column if not exists route_calculated_at timestamptz;
alter table public.projects add column if not exists network_revision bigint not null default 0;

alter table public.buildings add column if not exists design_flow_lps double precision;
-- Legacy demo rows stored facility flow (L/s) in specific_demand_lpd. Migrate
-- only unmistakably labelled treatment facilities; ordinary buildings remain
-- untouched because their daily demand cannot be inferred safely.
update public.buildings
set design_flow_lps = specific_demand_lpd,
    specific_demand_lpd = null
where design_flow_lps is null
  and specific_demand_lpd is not null
  and (upper(coalesce(label, '')) like 'ОС %' or upper(coalesce(label, '')) like 'OC %' or upper(coalesce(label, '')) like 'OS %');

alter table public.nodes add column if not exists system_type text;
alter table public.nodes add column if not exists design_flow_lps double precision;
alter table public.nodes add column if not exists invert_elevation_m double precision;
alter table public.nodes add column if not exists source_entity text;
alter table public.nodes add column if not exists data_source text;

-- The original MVP restricted node kinds to seven water-network values.
-- Keep the guard, but allow the explicit sewer/LNS topology persisted by the
-- engineering engine. The exact engineering kind is also retained in meta.
alter table public.nodes drop constraint if exists nodes_kind_check;
alter table public.nodes add constraint nodes_kind_check check (kind in (
  'source', 'junction', 'hydrant', 'valve', 'air_valve', 'drain', 'well',
  'ring', 'cross', 'building', 'facility_inflow', 'lns_inlet', 'lns_outlet',
  'outlet', 'manhole', 'terrain_break', 'treatment_facility',
  'pumping_station', 'gravity_inlet', 'pressure_outlet', 'chamber',
  'outfall', 'crossing', 'transition', 'inspection_node'
));

alter table public.pipes add column if not exists engineering_kind text;
alter table public.pipes add column if not exists system_type text;
alter table public.pipes add column if not exists parallel_count integer not null default 1;
alter table public.pipes add column if not exists alignment jsonb;
alter table public.pipes add column if not exists source_layer text;
alter table public.pipes add column if not exists source_entity text;
alter table public.pipes add column if not exists flow_direction text;
alter table public.pipes add column if not exists inner_diameter_mm double precision;
alter table public.pipes add column if not exists sdr double precision;
alter table public.pipes add column if not exists sn double precision;
alter table public.pipes add column if not exists pn double precision;
alter table public.pipes add column if not exists roughness_mm double precision;
alter table public.pipes add column if not exists slope double precision;
alter table public.pipes add column if not exists start_invert_m double precision;
alter table public.pipes add column if not exists end_invert_m double precision;
alter table public.pipes add column if not exists cover_m double precision;
alter table public.pipes add column if not exists design_flow_lps double precision;
alter table public.pipes add column if not exists velocity_mps double precision;
alter table public.pipes add column if not exists filling_ratio double precision;
alter table public.pipes add column if not exists pressure_m double precision;
alter table public.pipes add column if not exists calculation_status text not null default 'unverified';
alter table public.pipes add column if not exists data_source text;

alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit'
  ));

-- One RPC = one PostgreSQL transaction. A failed insert rolls back the delete,
-- so the UI can never be left with an empty/stale half-network.
drop function if exists public.replace_project_network(uuid, jsonb, jsonb, text, text, text, jsonb, jsonb);
create or replace function public.replace_project_network(
  p_project_id uuid,
  p_nodes jsonb,
  p_pipes jsonb,
  p_route_status text,
  p_algorithm_version text,
  p_input_hash text,
  p_warnings jsonb default '[]'::jsonb,
  p_blockers jsonb default '[]'::jsonb,
  p_report jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
set search_path = public, pg_temp
as $$
declare
  next_revision bigint;
begin
  if not public.is_project_owner(p_project_id) then
    raise exception 'project access denied';
  end if;
  if p_route_status not in ('blocked', 'preliminary', 'calculated') then
    raise exception 'invalid route status: %', p_route_status;
  end if;

  create temporary table route_node_map (
    engine_id text primary key,
    db_id uuid not null,
    payload jsonb not null
  ) on commit drop;

  insert into route_node_map (engine_id, db_id, payload)
  select item ->> 'id', gen_random_uuid(), item
  from jsonb_array_elements(coalesce(p_nodes, '[]'::jsonb)) item;

  delete from public.pipes where project_id = p_project_id;
  delete from public.nodes where project_id = p_project_id;

  insert into public.nodes (
    id, project_id, kind, label, x, y, ground_elevation, demand_lps,
    design_flow_lps, invert_elevation_m, system_type, building_id,
    source_entity, data_source, meta
  )
  select
    m.db_id,
    p_project_id,
    coalesce(m.payload ->> 'kind', 'junction'),
    coalesce(m.payload ->> 'label', m.engine_id),
    (m.payload ->> 'x')::double precision,
    (m.payload ->> 'y')::double precision,
    nullif(m.payload ->> 'groundElevation', '')::double precision,
    nullif(m.payload ->> 'designFlowLps', '')::double precision,
    nullif(m.payload ->> 'designFlowLps', '')::double precision,
    nullif(m.payload ->> 'invertElevationM', '')::double precision,
    m.payload ->> 'systemType',
    nullif(m.payload ->> 'buildingId', '')::uuid,
    m.payload ->> 'sourceEntity', m.payload ->> 'dataSource',
    jsonb_build_object('engineKind', m.payload ->> 'kind', 'engineId', m.engine_id)
  from route_node_map m;

  insert into public.pipes (
    project_id, from_node, to_node, length_m, diameter_mm, material,
    engineering_kind, system_type, parallel_count, alignment, source_layer,
    source_entity, flow_direction, inner_diameter_mm, sdr, sn, pn,
    roughness_mm, slope, start_invert_m, end_invert_m, cover_m,
    design_flow_lps, velocity_mps, filling_ratio, pressure_m,
    calculation_status, data_source, meta
  )
  select
    p_project_id,
    f.db_id,
    t.db_id,
    nullif(item ->> 'lengthM', '')::double precision,
    nullif(item ->> 'diameterMm', '')::double precision,
    item ->> 'material',
    item ->> 'kind',
    item ->> 'systemType',
    greatest(1, coalesce(nullif(item ->> 'parallelCount', '')::integer, 1)),
    item -> 'alignment',
    item ->> 'sourceLayer',
    item ->> 'sourceEntity', item ->> 'flowDirection',
    nullif(item ->> 'innerDiameterMm', '')::double precision,
    nullif(item ->> 'sdr', '')::double precision,
    nullif(item ->> 'sn', '')::double precision,
    nullif(item ->> 'pn', '')::double precision,
    nullif(item ->> 'roughnessMm', '')::double precision,
    nullif(item ->> 'slope', '')::double precision,
    nullif(item ->> 'startInvertM', '')::double precision,
    nullif(item ->> 'endInvertM', '')::double precision,
    nullif(item ->> 'coverM', '')::double precision,
    nullif(item ->> 'designFlowLps', '')::double precision,
    nullif(item ->> 'velocityMs', '')::double precision,
    nullif(item ->> 'fillingRatio', '')::double precision,
    nullif(item ->> 'pressureM', '')::double precision,
    coalesce(item ->> 'calculationStatus', 'unverified'),
    item ->> 'dataSource',
    jsonb_build_object('kind', item ->> 'kind', 'engineId', item ->> 'id')
  from jsonb_array_elements(coalesce(p_pipes, '[]'::jsonb)) item
  join route_node_map f on f.engine_id = item ->> 'fromNode'
  join route_node_map t on t.engine_id = item ->> 'toNode';

  update public.projects
  set route_status = p_route_status,
      route_algorithm_version = p_algorithm_version,
      route_input_hash = p_input_hash,
      input_data_hash = p_input_hash,
      route_warnings = coalesce(p_warnings, '[]'::jsonb),
      route_blockers = coalesce(p_blockers, '[]'::jsonb),
      calculation_warnings = coalesce(p_warnings, '[]'::jsonb),
      calculation_blockers = coalesce(p_blockers, '[]'::jsonb),
      route_report = coalesce(p_report, '{}'::jsonb),
      route_quality = coalesce(p_report, '{}'::jsonb),
      route_calculated_at = now(),
      network_revision = network_revision + 1
  where id = p_project_id
  returning network_revision into next_revision;

  return next_revision;
end;
$$;

create or replace function public.save_gravity_design(
  p_project_id uuid,
  p_result jsonb
)
returns uuid
language plpgsql
set search_path = public, pg_temp
as $$
declare
  item jsonb;
  run_id uuid;
begin
  if not public.is_project_owner(p_project_id) then raise exception 'project access denied'; end if;
  for item in select value from jsonb_array_elements(coalesce(p_result -> 'pipes', '[]'::jsonb)) loop
    update public.pipes
    set diameter_mm = nullif(item ->> 'diameterMm', '')::double precision,
        slope = nullif(item ->> 'slope', '')::double precision,
        design_flow_lps = nullif(item ->> 'flowLps', '')::double precision,
        velocity_mps = nullif(item ->> 'velocityMs', '')::double precision,
        filling_ratio = nullif(item ->> 'fillRatio', '')::double precision,
        calculation_status = case when jsonb_array_length(coalesce(item -> 'issues', '[]'::jsonb)) = 0 then 'calculated' else 'preliminary' end,
        meta = coalesce(meta, '{}'::jsonb) || jsonb_build_object(
          'flowLps', nullif(item ->> 'flowLps', '')::double precision,
          'velocityMs', nullif(item ->> 'velocityMs', '')::double precision,
          'slope', nullif(item ->> 'slope', '')::double precision,
          'fillRatio', nullif(item ->> 'fillRatio', '')::double precision
        )
    where project_id = p_project_id and meta ->> 'engineId' = item ->> 'id';
  end loop;
  insert into public.calc_runs (project_id, status, params, summary, finished_at)
  values (
    p_project_id,
    'done',
    jsonb_build_object('system', p_result ->> 'systemType', 'outletFlowLps', p_result -> 'outletFlowLps'),
    p_result,
    now()
  ) returning id into run_id;
  return run_id;
end;
$$;

notify pgrst, 'reload schema';
-- END 0012_engineering_route.sql

-- ============================================================
-- BEGIN 0013_manhole_catalog.sql
-- ============================================================
-- Parametric manhole/camera construction catalog. The payload remains JSONB
-- in datasets because component rules vary between verified product catalogs.
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit',
    'manhole_catalog'
  ));
-- END 0013_manhole_catalog.sql

-- ============================================================
-- BEGIN 0014_dataset_uniqueness.sql
-- ============================================================
-- AquaScheme: one canonical dataset row per project and kind.
--
-- Older clients used SELECT followed by INSERT/UPDATE, so concurrent saves
-- could create duplicate rows. Keep the most recently created row from each
-- duplicate group, then enforce the invariant used by the frontend's
-- update-then-insert flow and its 23505 conflict retry.
-- The table lock closes the race between deduplication and constraint creation.

begin;

lock table public.datasets in share row exclusive mode;

-- A basis checklist is a map of independently uploaded documents. Legacy
-- duplicate rows can therefore contain disjoint file keys. Merge those keys
-- into the newest canonical row before the generic deduplication below. A key
-- from a newer row wins deterministically over the same key in an older row.
with basis_rows as (
  select
    dataset.id,
    dataset.project_id,
    dataset.created_at,
    dataset.content,
    row_number() over (
      partition by dataset.project_id
      order by dataset.created_at desc, dataset.id desc
    ) as row_rank
  from public.datasets as dataset
  where dataset.kind = 'basis'
),
basis_file_values as (
  select
    dataset.project_id,
    file.key,
    file.value,
    row_number() over (
      partition by dataset.project_id, file.key
      order by dataset.created_at desc, dataset.id desc
    ) as file_rank
  from public.datasets as dataset
  cross join lateral jsonb_each(
    case
      when jsonb_typeof(dataset.content -> 'files') = 'object'
        then dataset.content -> 'files'
      else '{}'::jsonb
    end
  ) as file
  where dataset.kind = 'basis'
),
merged_basis_files as (
  select
    project_id,
    jsonb_object_agg(key, value order by key) filter (where file_rank = 1) as files
  from basis_file_values
  group by project_id
)
update public.datasets as canonical
set content = (
  case
    when jsonb_typeof(canonical.content) = 'object' then canonical.content
    else '{}'::jsonb
  end
) || jsonb_build_object('files', coalesce(merged.files, '{}'::jsonb))
from basis_rows as ranked
left join merged_basis_files as merged on merged.project_id = ranked.project_id
where canonical.id = ranked.id
  and ranked.row_rank = 1;

with ranked as (
  select
    id,
    row_number() over (
      partition by project_id, kind
      order by created_at desc, id desc
    ) as duplicate_rank
  from public.datasets
)
delete from public.datasets as dataset
using ranked
where dataset.id = ranked.id
  and ranked.duplicate_rank > 1;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.datasets'::regclass
      and conname = 'datasets_project_kind_unique'
  ) then
    alter table public.datasets
      add constraint datasets_project_kind_unique unique (project_id, kind);
  end if;
end;
$$;

commit;

notify pgrst, 'reload schema';
-- END 0014_dataset_uniqueness.sql

-- ============================================================
-- BEGIN 0015_basis_file_atomic.sql
-- ============================================================
-- AquaScheme: atomic merge of one initial-permitting-document file name.
-- Apply after 0014_dataset_uniqueness.sql.
--
-- A browser may upload two different basis documents concurrently. A normal
-- read/merge/write cycle can then lose one `content.files` key. This RPC locks
-- the basis row, merges the requested key inside PostgreSQL and preserves all
-- unrelated content. Legacy duplicate rows are merged and updated together.

create or replace function public.save_basis_file(
  p_project_id uuid,
  p_item_id text,
  p_file_name text,
  p_base_content jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  base_content jsonb;
  base_files jsonb;
  stored_content jsonb;
  stored_files jsonb;
  merged_content jsonb;
  has_rows boolean;
begin
  if not public.is_project_owner(p_project_id) then
    raise exception 'project access denied' using errcode = '42501';
  end if;

  if p_item_id is null or not (p_item_id = any (array[
    'assignment', 'apz', 'pdp', 'route_act', 'genplan_scheme',
    'topo', 'geology', 'vertical', 'tu'
  ]::text[])) then
    raise exception 'invalid basis item: %', coalesce(p_item_id, '<null>')
      using errcode = '22023';
  end if;

  if nullif(btrim(p_file_name), '') is null then
    raise exception 'basis file name is required' using errcode = '22023';
  end if;

  base_content := case
    when jsonb_typeof(p_base_content) = 'object' then p_base_content
    else '{}'::jsonb
  end;
  base_files := case
    when jsonb_typeof(base_content -> 'files') = 'object' then base_content -> 'files'
    else '{}'::jsonb
  end;

  loop
    -- SELECT ... FOR UPDATE serializes merges for an existing row. Under the
    -- legacy schema it locks every duplicate before their JSON is combined.
    perform 1
    from public.datasets
    where project_id = p_project_id
      and kind = 'basis'
    for update;
    has_rows := found;

    if has_rows then
      -- Merge top-level keys from all legacy rows. Later rows win only when
      -- the same key exists in more than one row; every distinct key remains.
      select coalesce(
        jsonb_object_agg(entry.key, entry.value order by dataset.created_at, dataset.id),
        '{}'::jsonb
      )
      into stored_content
      from public.datasets as dataset
      cross join lateral jsonb_each(
        case
          when jsonb_typeof(dataset.content) = 'object' then dataset.content
          else '{}'::jsonb
        end
      ) as entry
      where dataset.project_id = p_project_id
        and dataset.kind = 'basis';

      -- `files` needs its own deep merge; a shallow JSONB `||` would replace
      -- the whole object and recreate the lost-update bug.
      select coalesce(
        jsonb_object_agg(entry.key, entry.value order by dataset.created_at, dataset.id),
        '{}'::jsonb
      )
      into stored_files
      from public.datasets as dataset
      cross join lateral jsonb_each(
        case
          when jsonb_typeof(dataset.content -> 'files') = 'object' then dataset.content -> 'files'
          else '{}'::jsonb
        end
      ) as entry
      where dataset.project_id = p_project_id
        and dataset.kind = 'basis';

      -- Persisted database content wins over a possibly stale browser base.
      -- The requested item is the only key intentionally overwritten here.
      merged_content := base_content || stored_content;
      merged_content := jsonb_set(
        merged_content,
        '{files}',
        base_files || stored_files || jsonb_build_object(p_item_id, p_file_name),
        true
      );

      update public.datasets
      set content = merged_content
      where project_id = p_project_id
        and kind = 'basis';

      update public.projects set route_status = 'stale' where id = p_project_id;
      return merged_content;
    end if;

    merged_content := jsonb_set(
      base_content,
      '{files}',
      base_files || jsonb_build_object(p_item_id, p_file_name),
      true
    );

    begin
      insert into public.datasets (project_id, kind, content)
      values (p_project_id, 'basis', merged_content);
      update public.projects set route_status = 'stale' where id = p_project_id;
      return merged_content;
    exception
      when unique_violation then
        -- Another transaction inserted the canonical row after our empty
        -- check. Retry; the next iteration locks and merges that winner.
        null;
    end;
  end loop;
end;
$$;

revoke all on function public.save_basis_file(uuid, text, text, jsonb) from public;
grant execute on function public.save_basis_file(uuid, text, text, jsonb) to authenticated;

notify pgrst, 'reload schema';
-- END 0015_basis_file_atomic.sql

-- ============================================================
-- BEGIN 0016_pump_catalog.sql
-- ============================================================
-- Каталог насосов ЛНС. Как и каталог колодцев, хранится JSONB в datasets:
-- марка, подача, напор и мощность зависят от завода, и встроенный список
-- попал бы в спецификацию проектной документации как неподтверждённый факт.
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit',
    'manhole_catalog', 'pump_catalog'
  ));
-- END 0016_pump_catalog.sql

-- ============================================================
-- BEGIN 0017_title_block.sql
-- ============================================================
-- Организация и подписанты для основной надписи (ГОСТ Р 21.101-2020, форма 3,
-- графы 9–13). Модель штампа существовала, но графы заполнять было нечем:
-- данных организации и ответственных проект нигде не хранил.
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit',
    'manhole_catalog', 'pump_catalog', 'title_block'
  ));
-- END 0017_title_block.sql

-- ============================================================
-- BEGIN 0018_master_plan.sql
-- ============================================================
-- Диаметры по генплану (предварительная схема). Задание на проектирование
-- требует принять схему генплана за основу и обосновывать отклонения расчётом,
-- поэтому сами диаметры генплана обязаны храниться: без них сверять не с чем, а
-- расхождение проекта и схемы остаётся незамеченным до экспертизы.
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit',
    'manhole_catalog', 'pump_catalog', 'title_block', 'master_plan'
  ));
-- END 0018_master_plan.sql

-- ============================================================
-- BEGIN 0019_vertical_plan.sql
-- ============================================================
-- Проектные отметки вертикальной планировки.
--
-- Городской линейный объект проектируется от ПЛАНИРУЕМОЙ поверхности, а не от
-- существующего рельефа: схема вертикальной планировки задаёт отметки на
-- перекрёстках, и глубины заложения считаются от них. Пока отметок негде было
-- хранить, профиль строился по одной съёмке, а модуль их совмещения
-- (engine/src/norms/vertplan.ts) лежал без пути с экрана.
--
-- Хранятся отдельным видом, а не в 'topography': это разные поверхности, и
-- смешивать измеренное с проектным нельзя — по ним считаются разные величины.
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit',
    'manhole_catalog', 'pump_catalog', 'title_block', 'master_plan', 'vertical_plan'
  ));
-- END 0019_vertical_plan.sql

-- ============================================================
-- BEGIN 0020_gravity_basins.sql
-- ============================================================
-- Подтверждённая инженером разбивка трассы на самотёчные бассейны.
--
-- planGravityBasins даёт ПРЕДЛОЖЕНИЕ: куда ставить перекачку — вопрос
-- компоновки площадки, стоимости эксплуатации и согласований, и программа за
-- инженера его не решает. Но и держать решение негде было: неосуществимый
-- самотёк оставался стоп-фактором навсегда, и альбом объекта не собирался.
--
-- Хранится решение, а не расчёт: число перекачек и чем оно подтверждено.
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit',
    'manhole_catalog', 'pump_catalog', 'title_block', 'master_plan', 'vertical_plan',
    'gravity_basins'
  ));
-- END 0020_gravity_basins.sql

-- ============================================================
-- BEGIN 0021_technical_conditions.sql
-- ============================================================
-- Контрактные величины проекта: то, что задают технические условия.
--
-- Проектный диаметр спрашивался ДВАЖДЫ — отдельным полем в секции
-- реконструкции и отдельным в прогоне комплекта. Два независимых поля для
-- одной величины расходятся молча: инженер правит одно, второе остаётся
-- прежним, и два расчёта одного объекта дают разное.
--
-- Хранится не только значение, но и происхождение: величина из документа ТУ,
-- измеренная по чертежу или введённая руками — это разные основания, и в
-- аудите они не должны сливаться.
alter table public.datasets drop constraint if exists datasets_kind_check;
alter table public.datasets add constraint datasets_kind_check
  check (kind in (
    'topography', 'buildings', 'source', 'geology', 'seismic', 'normative',
    'equipment', 'region', 'drainage', 'basis', 'route_constraints', 'route_audit',
    'manhole_catalog', 'pump_catalog', 'title_block', 'master_plan', 'vertical_plan',
    'gravity_basins', 'technical_conditions'
  ));
-- END 0021_technical_conditions.sql
